In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print(b)

[1 2 3]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [2]:
#Returns a new array of given shape and type with zeros
c=np.zeros(2)
print(c)

#Returns a new array of given shape and type with ones
d=np.ones(4)
print(d)

e = np.ones(2, dtype=int)
print(e)

#Returns a new array of given shape and type without initializing entries
f=np.empty([4])
print(f)

#Returns an array with evenly spaced elements as per the interval
g=np.arange(7)
print(g)

h=np.arange(2,9,2)
print(h)

#Returns a new array with the deletion of sub-arrays
i=np.delete(h, 2)
print(i)

#Returns a sorted array in ascending order
z = np.array([19, 22, 34, 14, 55, 76, 47, 8])
print(z)
j=np.sort(z)
print(j)

[0. 0.]
[1. 1. 1. 1.]
[1 1]
[1. 1. 1. 1.]
[0 1 2 3 4 5 6]
[2 4 6 8]
[2 4 8]
[19 22 34 14 55 76 47  8]
[ 8 14 19 22 34 47 55 76]


In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
a=arr.ndim #dimension
b=arr.size #size
c=arr.shape #shape
print(arr) 
print("dimensions = ",a,"\nsize = ",b,"\nshape =",c)

#Shapes an array without changing the data of the array.
y = arr.reshape(3,2)
print("\nAfter reshaping\n",y)

[[1 2 3]
 [4 5 6]]
dimensions =  2 
size =  6 
shape = (2, 3)

After reshaping
 [[1 2]
 [3 4]
 [5 6]]


In [4]:
a=np.array(5)
print("A= ",a)
b=np.array([1,2,3])
print("B= ", b)

#Addition
addition= np.add(a,b)
print("\nAfter Addition =", addition)

#Subtraction
sub=np.subtract(b,a)
print("After Subtraction =",sub)

#Multiplication
mul=np.multiply (a,b)
print("After Multiplcation =",mul)

#Division
div=np.divide (b,a)
print("After Division =",div)

div1=np.divide (b,10)
print("After Division =",div1)

#Reciprocal
rec=np.reciprocal(div) 
print(rec)

#Power
pow=np.power(a,2)
print("after ^2 = ", pow)

A=  5
B=  [1 2 3]

After Addition = [6 7 8]
After Subtraction = [-4 -3 -2]
After Multiplcation = [ 5 10 15]
After Division = [0.2 0.4 0.6]
After Division = [0.1 0.2 0.3]
[5.         2.5        1.66666667]
after ^2 =  25


In [5]:
a= np.array ([1,2,3])
b= np.array ([3,5,7])

print("values of A =", a)
print("values of B =", b)

m=np.mod(a,b)
r=np.remainder(a,b)
print("\nvalues of MOD =", m)
print("values of REMAINDER =", r)

#Real and Imaginary numbers
c=np.array([-5.6j, 0.2j,11, 1+1j])
print("\n",c)

#Returns only real part
print("\nreal=",np.real(c))

#Returns only imaginary part
print("imaginary=",np.imag(c))

#Returns the conjugate
print("Conjugate=", np.conj(c))

values of A = [1 2 3]
values of B = [3 5 7]

values of MOD = [1 2 3]
values of REMAINDER = [1 2 3]

 [-0.-5.6j  0.+0.2j 11.+0.j   1.+1.j ]

real= [-0.  0. 11.  1.]
imaginary= [-5.6  0.2  0.   1. ]
Conjugate= [-0.+5.6j  0.-0.2j 11.-0.j   1.-1.j ]


In [6]:
d=np.array ([1.1,-5.32,123,-0.56,25.5,32])
print("\n",d)
print("\nafter rounding up\n", np.around(d))
print("\nafter rounding up to 1st decimal value\n", np.around(d,decimals=1))

#Floor round off
print("\nFloor round off")
print(np.floor(d))

#Ceiling round off
print("\nCeiling round off")
print(np.ceil(d))


 [  1.1   -5.32 123.    -0.56  25.5   32.  ]

after rounding up
 [  1.  -5. 123.  -1.  26.  32.]

after rounding up to 1st decimal value
 [  1.1  -5.3 123.   -0.6  25.5  32. ]

Floor round off
[  1.  -6. 123.  -1.  25.  32.]

Ceiling round off
[  2.  -5. 123.  -0.  26.  32.]
